// sidebars.js
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    {
      type: "category",
      label: "学习路径",
      collapsed: false,
      items: [
        {
          type: "category",
          label: "开发者 Developer Track",
          link: { type: "doc", id: "tracks/developer/index" },
          items: [{ type: "autogenerated", dirName: "tracks/developer" }],
        },
        {
          type: "category",
          label: "运营者 Operator Track",
          link: { type: "doc", id: "tracks/operators/index" },
          items: [{ type: "autogenerated", dirName: "tracks/operators" }],
        },
        {
          type: "category",
          label: "中小商家 Merchant Track",
          link: { type: "doc", id: "tracks/merchants/index" },
          items: [{ type: "autogenerated", dirName: "tracks/merchants" }],
        },
        {
          type: "category",
          label: "企业 Enterprise Track",
          link: { type: "doc", id: "tracks/enterprise/index" },
          items: [{ type: "autogenerated", dirName: "tracks/enterprise" }],
        },
      ],
    },

    {
      type: "category",
      label: "知识库",
      link: { type: "doc", id: "topics/index" },
      items: [{ type: "autogenerated", dirName: "topics" }],
    },

    {
      type: "category",
      label: "资源库",
      link: { type: "doc", id: "resources/index" },
      items: [{ type: "autogenerated", dirName: "resources" }],
    },

    {
      type: "category",
      label: "社区",
      link: { type: "doc", id: "community/index" },
      items: [{ type: "autogenerated", dirName: "community" }],
    },

    {
      type: "category",
      label: "企业服务",
      link: { type: "doc", id: "enterprise-services/index" },
      items: [{ type: "autogenerated", dirName: "enterprise-services" }],
    },

    {
      type: "category",
      label: "更新日志",
      link: { type: "doc", id: "changelog/index" },
      items: [{ type: "autogenerated", dirName: "changelog" }],
    },
  ],
};

module.exports = sidebars;
